---
title: "us covid"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("~/Desktop/DataScience Exam/US_covid")

library(dplyr)
library(ggplot2)
library(tidyr)
library(tidyverse)
library(lubridate)
library(tsibble)
library(tsibbledata) # for accessing time series data from the book
library(feasts)
library(fpp3)
library(fabletools)
library(fable)
library(distributional)
library(lme4)


library(tis)
install.packages("prophet")
library(prophet)

install.packages("rstan")
library(rstan)
```
# Importing the US covid data 
```{r}
us_covid19_daily <- read_csv("archive (1)/us_covid19_daily.csv")
us_states <- read_csv("archive (1)/us_states_covid19_daily.csv", col_types = cols(date = col_double()))

us_daily <- us_covid19_daily
us_daily$date <- as.character(us_covid19_daily$date)
us_states$date <- as.character(us_states$date)

us_daily %>%
  mutate(date = as_date(date, ymd(date))) %>%
  as_tsibble(index = date)

state_tsibble <- us_states %>% 
  mutate(date = as_date(date, ymd(date))) %>%
  as_tsibble(key = state, index = date)

us_daily$positive <- as.numeric(us_daily$positive)


```
# importing and merging gdp and population data 
```{r}
gdp <- read_delim("~/Desktop/DataScience Exam/US_covid/gdp.csv", ";", escape_double = FALSE, trim_ws = TRUE)
abriviations <- read_delim("~/Desktop/DataScience Exam/US_covid/abriviations.csv",";", escape_double = FALSE, trim_ws = TRUE)

try <- merge(gdp, abriviations, by.x = "state_name", by.y = "state_name", all =TRUE)
gdp_states <- subset(try, select = -state.x)


gdp_states$gdp_capita <- as.character(gdp_states$gdp_capita)

gdp_states$gdp_capita = gsub("\\$", "", gdp_states$gdp_capita)
gdp_states$gdp_capita = gsub("\\,", ".", gdp_states$gdp_capita)

gdp_states$gdp_capita <- as.numeric(gdp_states$gdp_capita)


write_csv(try, "gdp_states_cleaned.csv")


desity <- read_delim("~/Desktop/DataScience Exam/US_covid/desity.csv", ";", escape_double = FALSE, trim_ws = TRUE)
population <- read_delim("~/Desktop/DataScience Exam/US_covid/population.csv", ";", escape_double = FALSE, col_types = cols(population = col_number()), trim_ws = TRUE)

demographics <- merge(population, desity, by.x = "state_name", by.y = "state_name", all =TRUE)

demographics <- merge(gdp_states, demographics, by.x = "state_name", by.y = "state_name", all =TRUE)

demographics <- na.omit(demographics) 

write_csv(demographics, "demographics_clean.csv")

```

# trying to merge demographics with dataset 
```{r}
full <- merge(state_tsibble, demographics, by.x = "state", by.y = "state.y", all =TRUE)

fully <- full %>% 
  mutate(date = as_date(date, ymd(date))) %>%
  as_tsibble(key = state, index = date)

fully$population_density <- as.numeric(fully$population_density)

write_csv(fully, "fully_merged_6may.csv")

```



```{r}


ggplot(us_daily, aes(Date, positive)) +
  geom_line()

b <- us_states %>%
  ggplot(aes(date, positive, color = state)) +
  geom_line()
b

autoplot(us_tibble, positive)

```

```{r}

us_daily <- us_daily%>%
  select(date, positive, )
log_trans <- us_daily %>%
  summarise(log = log(positive))

log_trans$log <- 



dcmp <- log_trans %>%
  model(stl = STL(log))
components(dcmp)

components(dcmp) %>% autoplot()
```

```{r}
components(dcmp) %>%
  as_tsibble() %>%
  autoplot(positive, colour = "gray") +
  geom_line(aes(y=season_adjust), colour = "#0072B2") +
  labs(y = "Persons (thousands)",
       title = "Total employment in US retail")
```



```{r}

states <- fully %>%
  group_by(state) %>%
autoplot(fully, positive)+
  labs(title = "COVID positive test / population")


sates <- fully %>%
  group_by(state) %>%
  summarise(pos = sum(positive/population))
autoplot(sates, pos)+
  labs(title = "COVID positive test / population")

sates_dens <- fully %>%
  group_by(state) %>%
  summarise(positive = sum(positive/population_density))
autoplot(sates_dens, positive)+
  labs(title = "COVID positive test / population desity")

```

```{r}
death <- fully %>%
  group_by(state) %>%
  summarise(death_ = sum(death/population))
autoplot(death, death_)+
  labs(title = "COVID death / population")
```


```{r}
pos-recovered <- fully %>%
  group_by(state) %>%
  summarise(death_ = sum(death/population))
```

```{r}

sates$log <- log(sates$pos)

lm <- lm(pos ~ date, data = sates)
summary(lm)

lm$coefficients[2]

california <- state_tsibble %>%
  filter(state == "CA")

NY <- state_tsibble %>%
  filter(state == "NY")

lm <- lm(positive ~ date, california)
summary(lm)

lm2 <- lm(positive ~ date, NY)
summary(lm2)

growth.rate(california$positive, lag = 1, simple = T)





```
```{r}
us_all <- us_daily %>% 
  select(date, positive)

qplot(date, positive, data=us_all, main = "Total positive cases in the US")
```
```{r}
ds <- us_all$date
y <- us_all$positive

df <- data.frame(ds, y)

m <- prophet(df)

future <- make_future_dataframe(m, period = 28)
forecast <- predict(m, future)

plot(m, forecast)
dyplot.prophet(m, forecast)
```
```{r}
#model performance 
prophet_plot_components(m, forecast)
pred <- forecast$yhat[1:320]
actual <- m$history$y
plot(actual, pred)
summary(lm(pred~actual))

```

```{r}

fully_df <- as.data.frame(fully)



hello <- fully_df %>% 
  group_by(state) %>%
  select(state, date, positive, gdp, gdp_capita, population, population_density)

hello <- na.omit(hello)


hey <- hello %>% group_by(state) %>%
  summarise(pos = max(positive))

hi <- merge(demographics, hey, by.x="state.y", by.y="state")

lm_full <- glm(pos ~ population + population_density + gdp_capita + gdp, data=hi)
summary(lm_full)

lm_gdp <- glm(pos ~ population_density + gdp_capita, data=hi)
summary(lm_gdp)


```


```{r}
fit <- t_df %>%
  model(arima_person = ARIMA(Lix ~ Person),
        arima_no = ARIMA(Lix))
  
fit %>% select(arima_person) %>% report()


fit <- fully %>% 
  group_by(state)%>%
  model(arima_state = ARIMA(positive ~ gdp_capita),
        arima_no = ARIMA(positive))

fit %>% select(arima_state) %>% report()
```

